import './globals.css'
import { Inter, Poppins, Playfair_Display } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] });
const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], variable: "--poppins-font" });
const playfairDisplay = Playfair_Display({subsets: ['latin'],  weight: ["400", "500", "600", "700", "800", "900"], variable: "--playfair-font"});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${playfairDisplay.variable}`}>{children}</body>
    </html>
  )
}
